### ISSUE TITLE
IllegalArgumentException when dismiss

### ISSUE THREAD

**Issue by jesielin** [JohnPersano/SuperToasts#69]
05-19 11:29:33.946    2878-2878/com.zihexin.cwapp E/cwapp﹕ CrashHandler.java:[saveCrashInfo2File:127]java.lang.IllegalArgumentException: View=android.widget.LinearLayout{42d16508 V.E..... ......I. 0,0-436,168 #7f0b01bf app:id/root_layout} not attached to window manager
            at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:389)
            at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:318)
            at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
            at com.github.johnpersano.supertoasts.ManagerSuperToast.removeSuperToast(ManagerSuperToast.java:210)
            at com.github.johnpersano.supertoasts.ManagerSuperToast.handleMessage(ManagerSuperToast.java:152)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jendakol** [comment]
This happens when toast is shown but the activity (which has shown it) is already hidden.

**Comment by JohnPersano** [comment]
jesielin,
Thanks for the input. This is a frustrating issue but I believe it is fixed in version 2.0. If you have the same issue with the new version please let me know.
Thanks,
- John
